// webapp/components/Map.tsx
import ReactMapGL, { MapProvider, Marker, useMap, ViewState } from 'react-map-gl';
import { MAPBOX_ACCESS_TOKEN } from '../environment';
import { ParkingLotID, ParkingLot } from '../lib/types';

type MapMarkerProps = {
  parkingLot: [ParkingLotID, ParkingLot],
  onClick: () => void,
}

const MapMarker = ({ parkingLot, onClick }: MapMarkerProps) => (
  <Marker
    key={parkingLot[0]}
    longitude={parkingLot[1].metadata.location.longitude}
    latitude={parkingLot[1].metadata.location.latitude}
    anchor="bottom"
    onClick={onClick}
  >
    <img alt="marker" src="/parking-lot-marker.png" width={48} />
  </Marker>
)

export type MapView = ViewState & { width: number; height: number; };

type MapProps = {
  parkingLots: Record<ParkingLotID, ParkingLot>,
  mapView: MapView,
  selectParkingLot: (id: ParkingLotID | undefined) => void
}

const Map = ({ parkingLots, selectParkingLot, mapView }: MapProps) => {
  let { mymap: map } = useMap();

  return (
    <ReactMapGL
      mapboxAccessToken={MAPBOX_ACCESS_TOKEN}
      id="mymap"
      initialViewState={{
        longitude: 18.64,
        latitude: 54.35,
        zoom: 10
      }}
      style={{ width: "fit" }}
      mapStyle="mapbox://styles/mapbox/navigation-day-v1"
    >
      {Object.entries(parkingLots).map((parkingLot) => (
        <MapMarker key={parkingLot[0]} parkingLot={parkingLot} onClick={() => selectParkingLot(parkingLot[0])} />
      ))}
    </ReactMapGL>
  );
}

const MapRoot = (props: MapProps) => (
  <MapProvider>
    <Map {...props} />
  </MapProvider>
)


export default MapRoot;

// webapp/src/components/Map.svelte
<script lang="ts">
	import { MAPBOX_ACCESS_TOKEN } from "$lib/environment";
	import mapboxgl from "mapbox-gl";
	import { onMount } from "svelte";
    import 'mapbox-gl/dist/mapbox-gl.css';
	import type { ID, ParkingLot } from "$lib/types";
	import { currentMap } from "$lib/store";
    
    export let parkingLots: Record<ID, ParkingLot>;

    onMount(() => {
        mapboxgl.accessToken = MAPBOX_ACCESS_TOKEN;
        const map = new mapboxgl.Map({
            container: "map-container",
            style: "mapbox://styles/mapbox/streets-v11",
            center: [18.64, 54.35],
            zoom: 10,
        });
        currentMap.set(map);
        
        Object.entries(parkingLots).map(([id, parkingLot]) => {
            const [longitude, latitude] = parkingLot.metadata.geometry.coordinates;
            return new mapboxgl.Marker()
                .setLngLat([longitude, latitude]);
        }).forEach((marker) => marker.addTo(map));

    });
</script>

<div id="map-container"></div>
<style>
    #map-container { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
